<div class="festi-checkout-steps-wizard-baner">
    <a class="festi-cart-go-woocart button-primary" href="http://codecanyon.net/item/woocommerce-multistep-checkout-wizard-pro/8674984?ref=Festi-Team">
        <?php _e('GET PRO VERSION!', $this->_languageDomain); ?>
    </a>
    <h1>
        <?php _e('MultiStep Checkout Wizard Lite', $this->_languageDomain); ?>
    </h1>
    <p>
       <?php _e('Why go PRO? Ability to customize any element, disable steps, changing styles and many more', $this->_languageDomain); ?>
    </p>
</div>