<div class="festi-checkout-steps-wizard-container">
<?php 
    echo $themsBlock;
    echo $settingsBlock;
?>  
    
</div>

<div id="optionsframework-sidebar" class="metabox-holder">
    <div id="optionsframework" class="postbox">
        <h3>Community</h3>
          <div class="inside">
              <div id="social-share">
                  <?php echo $this->fetch("facebook_button.phtml");?>
                  <br /><br />
                  <?php echo $this->fetch("twitter_button.phtml");?>
              </div>
                <p>If you like this plugin, we'd appreciate any of the following:</p>
                <ul>
                    <li><a class="button" href="http://wordpress.org/support/view/plugin-reviews/woocommerce-multistep-checkout-wizard-lite" target="_blank">Rate this Plugin</a></li>
                    <li><a class="button" href="https://www.facebook.com/pages/Festi-Team/506350546133286" target="_blank">Follow on Facebook</a></li>
                    <li><a class="button" href="https://twitter.com/festiio/" target="_blank">Follow on Twitter</a></li>
                </ul>
          </div>

    </div>
        </div>