<?php

/**
 *  * You are allowed to use this API in your web application.
 *
 * Copyright (C) 2013 by customweb GmbH
 *
 * This program is licenced under the customweb software licence. With the
 * purchase or the installation of the software in your application you
 * accept the licence agreement. The allowed usage is outlined in the
 * customweb software licence which can be found under
 * http://www.customweb.ch/en/software-license-agreement
 *
 * Any modification or distribution is strictly forbidden. The license
 * grants you the installation in one application. For multiuse you will need
 * to purchase further licences at http://www.customweb.com/shop.
 *
 * See the customweb software licence agreement for more details.
 *
 */

require_once 'Customweb/Database/Migration/IScript.php';

class BarclaycardCw_Migration_1_1_0 implements Customweb_Database_Migration_IScript {

	public function execute(Customweb_Database_IDriver $driver){
		$result = $driver->query("SHOW TABLES LIKE 'barclaycardcw_storage'");
		$entityManager = BarclaycardCwUtil::getEntityManager();
		if ($result->getRowCount() <= 0) {
			$schema = $entityManager->generateEntitySchema('BarclaycardCw_Storage');
			$entityManager->getDatabaseDriver()->query($schema)->execute();
		}
		else {
			//We already have a tabel generated by the entity manager but it ignored the wordpress table prefix
			$tableName = $entityManager->getTableNameForEntityByClassName('BarclaycardCw_Storage');
			$driver->query("RENAME TABLE `barclaycardcw_storage` TO `" . $tableName . "`")->execute();
		}
		return true;
	}
}